### ISSUE TITLE
Problem when trying to run demo on HR-TEM notebook 

### ISSUE THREAD

**Issue by Espendb** [HamishGBrown/py_multislice#4] opened 2021-04-07 13:41 UTC
Hi Hamish 
I was trying to run the tutorial / example HR-TEM notebook. 
I have, however, run into some problems. Not sure if this has anything to do with me lacking the FAC or some other issues. 
I am woking on a Mac (big sur). Let me know what sort of info you need from me.
<img width="2168" alt="Screenshot 2021-04-07 at 15 40 57" src="https://user-images.githubusercontent.com/22670911/113876048-a7812480-97b7-11eb-835c-afcbe1626f11.png">

**Comment by HamishGBrown** [comment] 2021-04-23 03:58
Hi @Espendb, the problem is forward compatibility with pytorch newer version from 1.6 onward  have a whole fft module (so torch.fft is a module) whilst the older versions of pytorch just had fft and ifft functions called via torch.fft and torch.ifft. I'll try think of a quick fix for this but I might have to rework the code a bit to work with the newest pytorch

**Comment by HamishGBrown** [comment] 2021-04-23 04:08
If you could try downgrading your pytorch to 1.2.0 it might be made to work

**Comment by Espendb** [comment] 2021-04-23 10:14
Thanks @HamishGBrown - this worked like a charm.  I can now run the tutorial without any issues. Will try it out on "a real " structure next :)

**Comment by AndrewHerzing** [comment] 2021-12-03 03:08
Are there any plans to make the code compatible with newer versions of PyTorch?  I am having difficulty running v1.2.0 with my hardware.

**Comment by HamishGBrown** [comment] 2021-12-09 05:33
@AndrewHerzing, I've already begun work on readying the code for pytorch 1.8 onward. I'll have a few days to spend on it in the coming weeks but the project has turns out to be a little larger than I first perceived.

**Comment by AndrewHerzing** [comment] 2021-12-09 14:34
That is excellent news.  Please let me know if there is any way I can help via testing, etc.

**Comment by HamishGBrown** [comment] 2022-01-21 06:15
@AndrewHerzing, @Espendb I have a version of py_multislice that runs with pytorch 1.8. Still working on one or two niggling bugs but it passes all the tests and runs all the notebooks. Would you be interested in trying it? The ionization workflows are still to be updated since the FAC code changed under my feet and i'm likely to just copy what abTEM did and go with GPAW instead.  Apologies if that was the feature you were after.

**Comment by DISORDER-Espen** [comment] 2022-01-21 15:31
Hi @HamishGBrown (Different username due to starting my own research group :) ) Anyway, would be interested in trying it for sure.

**Comment by AndrewHerzing** [comment] 2022-01-21 18:10
Yes, absolutely.

**Comment by HamishGBrown** [comment] 2022-01-27 04:13
I've just pushed the master branch. I've tested on pytorch 1.7,1.8 and 1.10 and even works on a GTX 3090 now. Let me know how you go.

**Comment by HamishGBrown** [comment] 2022-03-01 23:19
Closing this issue, but feel free to reopen if the fix turns out to be specific to the systems I've used.

**Closed by HamishGBrown** 2022-03-01 23:19 UTC
